mystring ='''
Paul Adrien Maurice Dirac OM FRS[6] (/dɪˈræk/; 8 August 1902 – 20 October 1984) was an English mathematical and theoretical physicist who is considered to be one of the founders of quantum mechanics and quantum electrodynamics.[7][8] He is credited with laying the foundations of quantum field theory.[9][10][11][12] He was the Lucasian Professor of Mathematics at the University of Cambridge, a professor of physics at Florida State University and the University of Miami, and a 1933 Nobel Prize in Physics recipient.

Dirac graduated from the Universty of Bristol with a first class honours Bachelor of Science degree in electrical engineering in 1921, and graduated from the University of Cambridge with a PhD in physics in 1926, writing the first ever thesis on quantum mechanics.[8][13]

Dirac made fundamental contributions to the early development of both quantum mechanics and quantum electrodynamics, coining the latter term.[11] Among other discoveries, he formulated the Dirac equation in 1928, which describes the behaviour of fermions and predicted the existence of antimatter,[14] and is considered one of the most important equations in physics,[9] with it being considered by some to be the "real seed of modern physics".[15] He wrote a famous paper in 1931,[16] which further predicted the existence of antimatter.[17][18][14] Dirac shared the 1933 Nobel Prize in Physics with Erwin Schrödinger "for the discovery of new productive forms of atomic theory".[19] He was the youngest ever theoretician to win the prize until T. D. Lee in 1957.[20] He also made significant contributions to the reconciliation of general relativity with quantum mechanics. His 1930 monograph, The Principles of Quantum Mechanics, is considered to be one of the most influential texts on quantum mechanics.[21]

Dirac's contributions were not only restricted to quantum mechanics. He contributed to the Tube Alloys project, the British programme to research and construct atomic bombs during World War II.[22][23] Furthermore, Dirac made fundamental contributions to the process of uranium enrichment and the gas centrifuge,[24][25][26][23] and whose work was deemed to be "probably the most important theoretical result in centrifuge technology".[27] He also contributed to cosmology, putting forth his large numbers hypothesis.[24][28][29][30][31] Dirac is also seen as having anticipated string theory well before its inception, with his work on the Dirac membrane and Dirac–Born–Infeld action, amongst other contributions.[32][33]
'''


valstring = '''
"Cardigan"
Duration: 22 seconds.0:22
Swift uses her lower register in "Cardigan" (2020).[323]
"Lavender Haze"
Duration: 18 seconds.0:18
"Lavender Haze" (2022) features Swift's falsetto vocals in the refrain.[324]
Problems playing these files? See media help.
Swift possesses a mezzo-soprano vocal range,[325] and a generally soft but versatile timbre.[326][327] As a country singer, her vocals were criticized by some as weak and strained compared to those of her contemporaries.[328] Swift admitted her vocal ability often concerned her in her early career and has worked hard to improve.[329] Reviews of her vocals remained mixed after she transitioned to pop music with 1989; critics complained that she lacked proper technique but appreciated her usage of her voice to communicate her feelings to the audience, prioritizing "intimacy over power and nuance".[330] They also praised her for refraining from correcting her pitch with Auto-Tune.[331]
The Los Angeles Times remarked that Swift's defining vocal feature is her attention to detail to convey an exact feeling—"the line that slides down like a contented sigh or up like a raised eyebrow".[332] With Reputation, critics noted she was "learning how to use her voice as a percussion instrument of its own",[333] swapping her "signature" expressive vocals for "cool, conversational, detached" cadences and rhythms similar to hip hop and R&B styles.[334][335][336] Alternative Press stated that her "evocative" vocal stylings are more reminiscent of pop-punk and emo genres.[337]
Reviews of Swift's later albums and performances were more appreciative of her vocals, finding them less nasal, richer, more resonant, and more powerful.[304][338][339] With Folklore and Evermore, Swift received praise for her sharp and agile yet translucent and controlled voice.[340][341][342] Pitchfork described it as "versatile and expressive".[343] With her 2021 re-recorded albums, critics began to praise the mature, deeper and "fuller" tone of her voice.[344][345][346] An i review said Swift's voice is "leagues better now".[347] The Guardian highlighted "yo-yoing vocal yelps" and passionate climaxes as the trademarks of Swift's voice,[348] and that her country twang faded away.[349] Midnights received acclaim for Swift's nuanced vocal delivery.[350] She ranked 102nd on the 2023 Rolling Stone list of the 200 Greatest Singers of All Time.[327] In a review of the Eras Tour, The New Yorker critic Amanda Petrusich praised the clarity and tone of Swift's live vocals.[351] Musicologist Alyssa Barna said that Swift's timbre is "breathy and bright" in her upper register and "full and dark" in the lower.[222]
Songwriting
Further information: List of songs by Taylor Swift
Swift has been referred to as one of the greatest songwriters ever by several publications.[352][353][354] Literature scholars like Jonathan Bate and Stephanie Burt have noted that her literary and melodic sensibility and writing style are rare amongst her peers.[355][356] Swift's bridges are often noted as one of the best aspects of her songs,[357][358] earning her the title "Queen of Bridges" from Time.[359] Mojo described her as "a sharp narrator with a gift for the extended metaphor".[360]
In The New Yorker in 2011, Swift said she identifies as a songwriter first: "I write songs, and my voice is just a way to get those lyrics across".[12] Her personal experiences were a common inspiration for her early songs, which helped her navigate life.[361][362] Her "diaristic" technique began with identifying an emotion, followed by a corresponding melody.[363][364] On her first three studio albums, love, heartbreak, and insecurities, from an adolescent perspective, were dominant themes.[365][366] She delved into the tumult of toxic relationships on Red,[367] and embraced nostalgia and post-romance positivity on 1989.[292] Reputation was inspired by the downsides of Swift's fame,[368] and Lover detailed her realization of the "full spectrum of love".[369] Other themes in Swift's music include family dynamics, friendship,[370][371] alienation, self-awareness, and tackling vitriol, especially sexism.[279][372]
Her confessional lyrics received positive reviews from critics,[373][12][374] who highlighted their vivid details and emotional engagement, which they found uncommon in pop music.[375][376][377] Critics also praised her melodic compositions; Rolling Stone described Swift as "a songwriting savant with an intuitive gift for verse-chorus-bridge architecture".[378][379] NPR dubbed Swift "a master of the vernacular in her lyrics",[335] remarking that her songs offer emotional engagement because "the wit and clarity of her arrangements turn them from standard fare to heartfelt disclosures".[379] Despite the positive reception, The New Yorker stated she was generally portrayed "more as a skilled technician than as a Dylanesque visionary".[12] Tabloid media often speculated and linked the subjects of her songs with her ex-lovers, a practice reviewers and Swift herself criticized as sexist.[380][381][382] Aside from clues in album liner notes, Swift avoided talking about the subjects of her songs.[383]
On her 2020 albums Folklore and Evermore, Swift was inspired by escapism and romanticism to explore fictional narratives.[384] She imposed emotions onto imagined characters and story arcs, which liberated her from tabloid attention and suggested new paths for her artistry.[363] Swift explained that she welcomed the new songwriting direction after she stopped worrying about commercial success.[384] According to Spin, she explored complex emotions with "precision and devastation" on Evermore.[385] Consequence stated her 2020 albums convinced skeptics of her songwriting prowess, noting her transformation from "teenage wunderkind to a confident and careful adult".[358]
Swift divides her writing into three types: "quill lyrics", songs rooted in antiquated poeticism; "fountain pen lyrics", based on modern and vivid storylines; and "glitter gel pen lyrics", which are lively and frivolous.[386] Critics note the fifth track of every Swift album as the most "emotionally vulnerable" of the album.[387] Awarding her with the Songwriter Icon Award in 2021, the National Music Publishers' Association remarked that "no one is more influential when it comes to writing music today".[388] The Week deemed her the foremost female songwriter of modern times,[389] and the Nashville Songwriters Association International named her Songwriter-Artist of the Decade in 2022.[245] Swift has also published two original poems: "Why She Disappeared" and "If You're Anything Like Me".[390]
Performances
Further information: List of Taylor Swift live performances

Swift performing on the Reputation Stadium Tour in Seattle in May 2018
Journalists have described Swift as one of the best live performers. Often praised for her showmanship and stage presence,[391][392][393][394][395] Swift commands large audiences,[396][397][398] without having to rely on dance like her contemporaries do.[399] According to V magazine's Greg Krelenstein, she possesses "a rare gift of turning a stadium spectacle into an intimate setting", irrespective of whether she is "plucking a guitar or leading an army of dancers".[400] In a 2008 review of Swift's early performances, Sasha Frere-Jones of The New Yorker called Swift a "preternaturally skilled" entertainer with a vibrant stage presence, adding "she returned the crowd's energy with the professionalism she has shown since the age of fourteen."[401] In 2023, Adrian Horton of The Guardian noted her "seemingly endless stamina" on the Eras Tour,[402] and i critic Ilana Kaplan called her showmanship "unparalleled".[403]
Critics have highlighted Swift's versatility as an entertainer, praising her ability to switch onstage personas and performance styles depending on the varying themes and aesthetics of her albums.[404][405] Her concert productions have been characterized by elaborate Broadway theatricality and high technology,[406] and her performances frequently incorporate a live band, with whom she has played and toured since 2007.[407] Swift also often accompanies herself with musical instruments such as electric guitar;[408] acoustic guitar; piano;[409] and sometimes twelve-string guitar,[410][411] banjo,[412] or ukulele.[413] Interacting frequently with the audience, her solo acoustic performances are considered intimate and emotionally resonant, complementing her story-based lyrics and fan connection.[351][414] Lydia Burgham of The Spinoff opined that this intimacy remains "integral to her singer-songwriter origins".[415][409] Chris Willman of Variety called Swift "pop's most approachable superstar",[416] and the 21st century's most popular performer.[417]
Video and film
Further information: Taylor Swift videography
Swift emphasizes visuals as a key creative component of her music-making process.[418] She has collaborated with different directors to produce her music videos, and over time she has become more involved with writing and directing. She developed the concept and treatment for "Mean" in 2011[419] and co-directed the music video for "Mine" with Roman White the year before.[420] In an interview, White said that Swift "was keenly involved in writing the treatment, casting and wardrobe. And she stayed for both the 15-hour shooting days, even when she wasn't in the scenes."[421]
From 2014 to 2018, Swift collaborated with director Joseph Kahn on eight music videos—four each from her albums 1989 and Reputation. Kahn has praised Swift's involvement.[422] She worked with American Express for the "Blank Space" music video (which Kahn directed), and served as an executive producer for the interactive app AMEX Unstaged: Taylor Swift Experience, for which she won a Primetime Emmy Award for Outstanding Interactive Program in 2015.[423] Swift produced the music video for "Bad Blood" and won a Grammy Award for Best Music Video in 2016.[424]
Her production company, Taylor Swift Productions, is credited with producing all of her visual media starting with the 2018 concert documentary Reputation Stadium Tour.[425] She continued to co-direct music videos for the Lover singles "Me!" with Dave Meyers, and "You Need to Calm Down" (also serving as a co-executive producer) and "Lover" with Drew Kirsch,[426] but first ventured into sole direction with the video for "The Man" (which won her the MTV Video Music Award for Best Direction).[427] After Folklore: The Long Pond Studio Sessions, Swift debuted as a filmmaker with All Too Well: The Short Film,[245] which made her the first artist to win the Grammy Award for Best Music Video as a sole director.[428] Swift has cited Chloé Zhao, Greta Gerwig, Nora Ephron, Guillermo del Toro, John Cassavetes, and Noah Baumbach as filmmaking influences.[418]
Accolades and achievements
Further information: List of awards and nominations received by Taylor Swift

In 2009, Swift became the first country singer to win an MTV Video Music Award.
Swift's discography is a "critically hailed songbook", as per Time's Sam Lansky.[429] She has won 14 Grammy Awards (including four for Album of the Year—the most won by an artist),[430] an Emmy Award,[431] 40 American Music Awards (the most won by an artist),[432] 39 Billboard Music Awards (the most won by an artist—tying with Drake),[433] 118 Guinness World Records,[434] 23 MTV Video Music Awards (including four Video of the Year wins—the most by an act),[247] 12 Country Music Association Awards (including the Pinnacle Award),[435] eight Academy of Country Music Awards,[436] and two Brit Awards.[168] As a songwriter, she has been honored by the Nashville Songwriters Association,[63][437] the Songwriters Hall of Fame, and the National Music Publishers' Association and was the youngest person on Rolling Stone's list of the 100 Greatest Songwriters of All Time in 2015.[438][439] At the 64th BMI Awards in 2016, Swift was the first woman to be honored with an award named after its recipient.[440]
Commercially, from available data, Swift has amassed over 50 million album sales and 150 million single sales as of 2019,[441][442][443] and 114 million units globally, including 78 billion streams as of 2021.[444][445] The International Federation of the Phonographic Industry ranked her as the Global Recording Artist of the Year for a record three times (2014, 2019 and 2022).[446] Swift has the most number-one albums in the United Kingdom and Ireland for a female artist this millennium,[447][448] earned the highest income for an artist on Chinese digital music platforms (RMB 159,000,000 as of 2021),[449] and is the first artist to replace themselves at the top spot and occupy the entire top five[note 3] of the Australian albums chart.[452][453] Swift remains the world's highest-grossing female touring act ever, with cumulative ticket sales at $1.96 billion as of November 2023 according to Pollstar.[454] The Eras Tour is the highest-grossing tour of all time as of December 2023, and the first to surpass $1 billion in revenue.[455] Beginning with Fearless, each of her studio albums have opened with over one million global units.[456][457] Swift is the most streamed female act on Spotify and Apple Music.[458][459] On Spotify, she is the only artist to have received more than 200 and 250 million streams in one day (260 million on October 27, 2023),[460] and the only female act to reach 100 million monthly listeners.[234] The most entries and the most simultaneous entries for an artist on the Billboard Global 200, with 143 and 31 songs, respectively, are among her feats.[461][462]
In the US, Swift has sold over 37.3 million albums as of 2019,[443] when Billboard placed her eighth on its Greatest of All Time Artists Chart.[463] Eleven of her songs have topped the Billboard Hot 100.[257] She is the longest-reigning act of the Billboard Artist 100 (97 weeks);[464] the soloist with the most cumulative weeks atop the Billboard 200 (68);[465] the woman with the most Billboard 200 number-ones (13),[234] Hot 100 entries (232),[234][156] number-one debuts (6),[note 4] top-ten songs (49),[257] and weeks atop the Top Country Albums chart (101);[467] and the act with the most number-one songs on Pop Airplay (12) and Digital Songs (28).[468][469] Swift is the first woman to simultaneously chart five albums in the top 10 and eleven albums on the entire Billboard 200;[470][471] and the first act to occupy the top four spots and chart seven albums[note 5] in the top 10 on the Top Album Sales chart.[473][474] She is the second highest-certified female digital singles artist (and fifth overall) in the US, with 137.5 million total units certified by the Recording Industry Association of America (RIAA),[475] and the first woman to have both an album (Fearless) and a song ("Shake It Off") certified Diamond.[476] Swift is the only artist in Luminate history to have six albums sell over a million copies in a week.[477]
Swift has appeared in various power listings. Time included her on its annual list of the 100 most influential people in 2010, 2015, and 2019.[478] She was one of the "Silence Breakers" that the magazine spotlighted as Person of the Year in 2017 for speaking up about sexual assault,[479] and received the honor again in 2023 for her cultural domination that year.[429] Time described Swift as the first Person of the Year to be recognized for "achievement in the arts", as well as the first woman to be recognized and appear on a Person of the Year cover more than once.[480][481] In 2014, she was named to Forbes' 30 Under 30 list in the music category[482] and again in 2017 in its "All-Star Alumni" category.[483] Swift became the youngest woman to be included on Forbes' list of the 100 most powerful women in 2015, ranked at number 64.[484] In 2023, she was ranked by Forbes as the fifth-most powerful woman in the world, the first entertainer to place in the top five.[485] Swift received an honorary Doctor of Fine Arts degree from New York University and served as its commencement speaker on May 18, 2022.[245]
Cultural status
Main articles: Cultural impact of Taylor Swift and Public image of Taylor Swift

Swift at the 2010 Time 100 Gala
Swift has been credited with making a profound impact on the music industry, popular culture and the economy.[486][487] She dominates cultural conversations,[488][489] which has led publications to describe her as a cultural "vitality" or zeitgeist.[490][491][492] Her music, life and public image are points of attention in global celebrity culture.[297] Initially a teen idol,[493] she has been referred to as a pop icon;[312][494] publications describe her immense popularity and longevity as unwitnessed since the 20th century.[495][496] In 2013, New York magazine's Jody Rosen dubbed Swift the "world's biggest pop star" and opined that the trajectory of her stardom has defied established patterns. Rosen added that Swift "falls between genres, eras, demographics, paradigms, trends", leaving her contemporaries "vying for second place".[310] Critics regard Swift as a rare yet successful combination of the pop star and singer-songwriter archetypes.[497]
Her fans are known as Swifties.[266] Billboard noted only few artists have had her chart success, critical acclaim, and fan support.[498] Swift's million-selling albums are considered an anomaly in the streaming-dominated industry following the end of the album era in the 2010s.[499][500] Economist Alan Krueger described Swift as an "economic genius".[501]
Although labeled by the media in her early career as "America's Sweetheart" for her girl next door persona,[502][503] Swift has been accused by detractors of being "calculated" and manipulative of her image, a narrative bolstered by her 2016 dispute with West.[173][174] Critics have also noted that her personal life and career have been subject to intense misogyny and "slut-shaming",[504][505] as well as rampant media scrutiny and tabloid speculation.[506]
Swift's private jet use has drawn scrutiny for its carbon emissions.[507][508] In 2023, a spokesperson for Swift stated that she had purchased more than double the required carbon credits to offset all tour travel and personal flights.[509][510] In December 2023, Swift's lawyers sent a cease and desist letter to American programmer Jack Sweeney over tracking her private jet, citing safety concerns and stalking.[511][512] Swift has been a victim of numerous house break-ins and stalkers, some of whom were armed.[513][514]
Legacy
"You have different artists dominating different sectors of the industry: Some are huge at streaming, some are big draws on the road. But we're at this moment where there's no one better than Taylor Swift, whether that's on the radio, with streaming, ticket sales or just cultural impact."
– Jason Lipshutz, Billboard executive director, 2023[515]
Swift helped shape the modern country music scene,[516] having extended her success beyond the Anglosphere,[310][516] pioneered the use of internet (Myspace) as a marketing tool,[33][53] and introduced the genre to a younger generation.[517][310] Country labels have since become interested in signing young singers who write their own music;[518] her guitar performances contributed to the "Taylor Swift factor", a phenomenon to which an upsurge in guitar sales to women, a previously ignored demographic, is attributed.[519][520]
According to publications, Swift changed the music landscape with her genre transitions, a discography that accommodates cultural shifts,[521] and her ability to popularize any sound in mainstream music.[522] Lyrically, in being personal and vulnerable in her songs, music journalist Nick Catucci opined Swift helped make space for later singers like Billie Eilish, Ariana Grande, and Halsey to do the same.[523] Scholars have highlighted the literary sensibility and poptimist implications of Swift.[355][524] She has been credited with legitimizing and popularizing the concept of album "eras".[525][526] Swift is a subject of academic study and scholarly media research.[297] Various educational institutions offer courses on Swift in literary, cultural and sociopolitical contexts.[527][297]
Swift has influenced numerous music artists, and her albums have inspired a generation of singer-songwriters.[517][320][528] Journalists praise her ability to reform industry practices, noting how her actions changed streaming policies, prompted awareness of intellectual property in new musicians,[529][530] and reshaped ticketing models.[531] Various sources deem Swift's music a paradigm representing the millennial generation;[532] Vox called her the "millennial Bruce Springsteen",[533] and The Times named her "the Bob Dylan of our age".[534] Swift earned the title Woman of the Decade (2010s) from Billboard,[535] Artist of the Decade (2010s) at the American Music Awards,[536] and Global Icon at the Brit Awards for her impact.[445] Senior artists such as Paul McCartney,[537] Mick Jagger,[538] Madonna,[539] and Dolly Parton have praised her musicianship.[540] Carole King regards Swift her "professional grand daughter" and thanked Swift for "carrying the torch forward".[541] Springsteen called her a "tremendous" writer,[542] while Ringo Starr and Billy Joel considered Swift the Beatles' successor.[543][544] Britney Spears labeled Swift "the most iconic pop woman of our generation".[545]
Entrepreneurship
Media outlets describe Swift as a savvy businesswoman;[546][547] in 2024, she topped Billboard's annual Power 100 ranking of the top music industry executives.[548] Swift is known for her traditional album rollouts, consisting of a variety of promotional activities that Rolling Stone termed as an inescapable "multimedia bonanza".[549][550] Easter eggs and cryptic teasers became a common practice in contemporary pop music because of Swift.[551] Publications describe her discography as a music "universe" subject to analyses by fans, critics and journalists.[552][553][554] Swift maintains an active presence on social media and a close relationship with fans, to which many journalists attribute her success.[555][487][556] Her in-house management team is called 13 Management.[557]
Swift has endorsed many brands and businesses, having launched clothing lines with L.E.I. and Stella McCartney,[558][559] designed American Greetings cards and Jakks Pacific dolls,[560][561] released a number of fragrances with Elizabeth Arden,[562] and signed multi-year deals with AT&T and Capital One.[563][564] She was a spokesperson for the National Hockey League's Nashville Predators and Sony Cyber-shot digital cameras,[565][566] and became the global ambassador for New York City in 2014 and Record Store Day in 2022.[567][568]
Social activism
Further information: Political impact of Taylor Swift
Swift identifies as a pro-choice feminist,[569] and is a founding signatory of the Time's Up movement against sexual harassment.[570] Specifically, she criticized the US Supreme Court's decision to end federal abortion rights in 2022.[571] Swift also advocates for LGBT rights,[572] and has called for the passing of the Equality Act, which prohibits discrimination based on sex, sexual orientation, and gender identity.[573][574] She performed during WorldPride NYC 2019 at the Stonewall Inn, a gay rights monument, and has donated to the LGBT organizations Tennessee Equality Project and GLAAD.[575][576][577]
A supporter of the March for Our Lives movement and gun control reform in the US,[578] Swift is a vocal critic of white supremacy, racism, and police brutality.[579][569] Following the George Floyd protests, she donated to the NAACP Legal Defense and Educational Fund and the Black Lives Matter movement,[580] called for the removal of Confederate monuments in Tennessee,[581] and advocated for Juneteenth to become a national holiday.[582] In 2020, Swift urged her fans to check their voter registration ahead of elections, which resulted in 65,000 people registering to vote within one day of her post,[583] and endorsed Joe Biden and Kamala Harris in the US presidential election.[584] She has openly criticized former president Donald Trump.[585]
Wealth
Swift's net worth is estimated by Forbes and Bloomberg News at $1.1 billion as of October 2023, making her the first musician to achieve billionaire status "solely based on her songs and performances".[586][587] Forbes named her the annual top-earning female musician in 2016, 2019, 2021, and 2022.[588] She was the highest-paid celebrity of 2016 with $170 million—a feat recognized by the Guinness World Records as the highest annual earnings ever for a female musician,[589] which she herself surpassed with $185 million in 2019.[590] Overall, Forbes listed Swift as the highest-paid female artist of the 2010s, earning $825 million.[591] She has also developed a real estate portfolio worth $150 million as of 2023, with properties in Nashville; Tribeca, Manhattan; Los Angeles (Samuel Goldwyn Estate); and Rhode Island (High Watch).[592]
Philanthropy
Swift is known for her philanthropic efforts.[593] She ranked first on DoSomething's 2015 "Gone Good" list,[594] having received the Star of Compassion from the Tennessee Disaster Services and the Big Help Award from the Nickelodeon Kids' Choice Awards for her "dedication to helping others" and "inspiring others through action".[595][596] She donated $100,000 to the Red Cross to help the victims of the Iowa flood of 2008.[597] In 2009, she sang at BBC's Children in Need concert and raised £13,000 for the cause.[598] Swift has performed at charity relief events, including Sydney's Sound Relief concert.[599] In response to the May 2010 Tennessee floods, Swift donated $500,000.[600] In 2011, Swift used a dress rehearsal of her Speak Now tour as a benefit concert for victims of recent tornadoes in the US, raising more than $750,000.[601] In 2016, she donated $1 million to Louisiana flood relief efforts and $100,000 to the Dolly Parton Fire Fund.[602][603] Swift donated to food banks after Hurricane Harvey struck Houston in 2017 and at every stop of the Eras Tour in 2023;[604][605] she also directly employed local businesses throughout the tour and gave $55 million in bonus payments to her entire crew.[606][607] Swift donated $1 million for Tennessee tornado relief in 2020 and again in 2023.[608][609]
She is a supporter of the arts. A benefactor of the Nashville Songwriters Hall of Fame,[610] Swift has donated $75,000 to Nashville's Hendersonville High School to help refurbish the school auditorium,[611] $4 million to build a new education center at the Country Music Hall of Fame and Museum in Nashville,[612] $60,000 to the music departments of six US colleges,[613] and $100,000 to the Nashville Symphony.[614] Also a promoter of children's literacy, she has donated money and books to schools around the country.[615][616] In 2007, Swift partnered with the Tennessee Association of Chiefs of Police to launch a campaign to protect children from online predators.[617] She has donated items to several charities for auction, including the UNICEF Tap Project and MusiCares.[618] As recipient of the Academy of Country Music's Entertainer of the Year in 2011, Swift donated $25,000 to St. Jude Children's Research Hospital, Tennessee.[619] In 2012, Swift participated in the Stand Up to Cancer telethon, performing the charity single "Ronan", which she wrote in memory of a four-year-old boy who died of neuroblastoma.[620] She has also donated $100,000 to the V Foundation for Cancer Research[621] and $50,000 to the Children's Hospital of Philadelphia.[622] Swift has encouraged young people to volunteer in their local communities as part of Global Youth Service Day.[623]
Swift donated to fellow singer-songwriter Kesha to help with her legal battles against Dr. Luke and to actress Mariska Hargitay's Joyful Heart Foundation.[593][624] During the COVID-19 pandemic, Swift donated to the World Health Organization and Feeding America,[625] and supported independent record stores.[626][627] Swift performed "Soon You'll Get Better" on the One World: Together At Home television special, a benefit concert curated by Lady Gaga for Global Citizen to raise funds for the World Health Organization's COVID-19 Solidarity Response Fund.[628] In 2018 and 2021, Swift donated to the Rape, Abuse & Incest National Network in honor of Sexual Assault Awareness and Prevention Month.[593][629] She has made donations to her fans several times for their medical or academic expenses.[630] In December 2023, Swift attended Ramy Youssef's fundraiser for the Gaza Strip.[631]
Discography
Main articles: Taylor Swift albums discography, Taylor Swift singles discography, and List of songs by Taylor Swift
Studio albums
Taylor Swift (2006)
Fearless (2008)
Speak Now (2010)
Red (2012)
1989 (2014)
Reputation (2017)
Lover (2019)
Folklore (2020)
Evermore (2020)
Midnights (2022)
The Tortured Poets Department (2024)
Re-recorded albums
Fearless (Taylor's Version) (2021)
Red (Taylor's Version) (2021)
Speak Now (Taylor's Version) (2023)
1989 (Taylor's Version) (2023)
Filmography
Main article: Taylor Swift videography
This section lists select works only. Refer to the main article for further information.
Valentine's Day (2010)
The Lorax (2012)
The Giver (2014)
Cats (2019)
'''